version: '3.8'

services:
  # Frontend Nginx service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge