version: '3.8'

services:
  portfolio-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount for development hot-reloading
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      # Exclude node_modules from volume mounting
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped